apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: collector-shop-prod
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: collector-shop-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/alan-crts/collector-shop-backend:main
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: "production"
            - name: BETTER_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: BETTER_AUTH_BASE_URL
          envFrom:
            - secretRef:
                name: backend-secret
