apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: collector-shop-prod
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:password@db.collector-shop-prod.svc.cluster.local:5432/collector_shop?sslmode=disable
  BETTER_AUTH_SECRET: ABsUbdGctTW8vfORzukfmdik0hrGWdEA
  BETTER_AUTH_BASE_URL: http://api.collector-shop.local
