---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: collector-shop-prod
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBcT7uI33Mx7tVH3IhOkwBy40c6oguxLRVdPr2z4Ai4KuXOv55odqwQ1N4GT+lfHoyo4E3b/4icTsQppaow2IM6w3rTh2pWbc7rUQe1U+5FcNet+A4+vH/gSv9uy3rZYfOpoO9Aw8fpW9e/z7cnnPUdZe9WXzVQvTqSeFgQQ/QATSPzXfKsMNr9xn7LC0EuF9XY3lVp3+P4yKKdpwdP66RcSKbfgOzlKRGbnEXTA1ccxfPL2KftIlrTnxnxbRUySdJ+IwZOq92H9u6wOMIVGZHAGgCajdYdV3hRt05AwCgJ8z8IwhaT7P8hV7PLIdgGlwcTPBQR8P/++CPP+Uw2ArXIa0Ly/JyTEa6sPbmDQoZoqS0DEh+gUpcNyGt10uIp5A1I93FP3IJPaNxbj9MfJXsN4ojyzvNiR0b9/y1zQijSeWqxGUG1EzOj7ijZsLQPe8rtkhKdoEnWNFiSzSGJ8UijkqWw5WFfupzDeUmlQVcyZ5uqSI3sWJslZLZ/Bot4jFt2oLuVAtrCa71rB/TztVxsr6TWwNpGC4pSNwqfyMZV4xCjbJCoI4VsV5ikh35xFsEL6UWeqZvXmtpekb+5it7CVXnq6yLzBNlqdAnIkY7GIaxvqe2FeWUiAVDCoH71VPlmujIk8jn8p7COiOzrwa29PGnH7uj/3CyQvQGcvsIwnQ4xrX0fsZmguL6Cdwumvp7VEmtfGgwtclxhOQ==
    MINIO_ROOT_USER: AgBM70LfmamsJ4t2J7r23XxUAGzidNhgXQoyXm1GKXAV/SQyJmoRSr/7ie1RFKlvKN4LBhjQDA4mKoBv2/MmTK/PQcsmgAkgd+2OHMcdsDDYozvCW9te8ysWl6AlqWQKLY4Ow+zSXUlcbPaOPSbnwjLm++2WbLCYuFZSuQE2pYy//QElkxv7mkvk3MdQHvKLuIRQd6hx+VtI0VizPV+pRTTLTlK13FBcXH3zDQDgrvN2CTNkOQznZm4INmxjPBkx/gwaOy3mHAZYcRUSND3AzlqnLyLdMjlvHgsOyadhNLud4QBNfwqEB4yvOy0Hq3nttUDRcyNhNRnkU4sL+cvnllpO81sArJuJJ0EW6jftBF6R3jth/LFF/8v3Z3QE58y2UnAfDjXJ6DvIyVHYoLQVcf+2lhi7Xoyw4Lvytw00RqbnBBtyn2k5fzeaoUQxgXEDAuRd9AxCABerMNiB5oDOx3pRj5JdfDWYu7ZyBsg5W9wnsCnATG6Ev2Nue8WQew6Lb9sqz0nQaGpbtobmMzKdpu5IHbHbSOjeozkii7E5aq9IS64WB2xrvV3H0XWdFdPtzHIC1Yi5yfGOJeXeMQDttQ4GlhGHMV7WKc49gSCrqW6+bkrSHEu7GN2auM3IA3cyycrc7Q/0KjnjUc57DqrWkhe8kuTSruRIRWrL9N0r/aKG/cSotZmzmDF6+lE9B3s92FzR9Z34fw==
  template:
    metadata:
      name: minio-secret
      namespace: collector-shop-prod
    type: Opaque
