---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: collector-shop-prod
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAMPQXVIAHvZF6KAZdmK/yLdvHU7BiueVvFUqnvFm2oKdzG0QBYYjwSgtcHGGpqZ3mKm6xuieCwBQGBdd9KQhfm70EjPy5tvPPpUH1WMFbFNg6z8dqCkSglncjSPJFpNE0ik8T4ISCfERoKqx1letB96UDygYk4rNVovt96stcBprO0lUQ/EcNxBoFwJUsVCD5jFLfzdjbFvraUEaDfwqRfmisUamL5l55K8VIUu3FeQR2v3mJa73vhUNdcEGvqph3X9MsHAvO23+aChkvzwkWiB3PzDuPyBb1owvubZ+XSq5TxeFSt5lG9jwfV8QQe38+owe6Lgzk1Xj1xQ43bOPkxckMNlHmOvtP6DUWma4OAVDii5/q3rujcAr/6jAt/JSbvwwWLT4Y0tSnlpb4pQOZis58XXPPb3e584jUX1Q++lKqcBmZuZGXo1h/iSFBQnUgn3Ax+JxjUU1dC9GQ7eh3Ru0eVqUgkKb0XePQROAQFOK1w+o9Lk5rP5tBhmiY2e6C8aIsRdtBiygFtJIZNNLukXF77bfSzaee7cmg4UTuELZK9sjq2EuY1Ha2PbISNkiXJlNdxT62X2GaqdYlKKUts9kxNe9ClqSg9Od8xFODoEpS6XC/Dvm+r7/Gw8QiDBr/krttyXJjgIzmkBfPfimi3z+GDCmEn77rQeVmu9/J+iXEj0RqC6toYdcmQ+4J88ZTontTqFA4Se4u5qw==
    MINIO_ROOT_USER: AgBaXfFts2tzjyf8REnCKEjaWjILRe44LjZ11q55XMTywH5gNFHQAIXNPCqou07T6XCVHSdUPtjPdZiEriF/lh7hZOFTA9Gmi/B4oxQORiu7KYbT6PPFaF6Nij1CAchTAPJqTNygOVN8Z7UlrUY39uHUNLhvWMVFGQ1KILaNjLJLGaQ+vvxk+wJoMkHpKNivIGdwG6Cr+u8SvMJzZNRxYVOs9viKkrk99ftf12RzMstX4bS5aytUvF6MkxIPwUU7Qqw09NB2WByo1gv77kt7ZTzfqf8K1gSFtUuKxeBdm7wd8rU6Faf7LVVG6H5Jd9tBHbFwB01Fv/1glkiGn7QF2RhJVAxVnHfqu1pgqxpyz+Mlfp+dGRMQjryYtvFHsrLvD4MTvzje8glJqy/Lme367JvPvSNIxbsP6gfoNpY6CiYPFUtm5EQfAYV2Wox/6zYdEJ6dNNe6q/hM9A6LQ1VEKgsnR4mIJkvbib0Il1kvr9jocR5HIktuXvNVidD9UYh1ploAuDDBOls4fDYY/QBkzijv+253cs7arCnc4An8TO35QmfVfSyKoT3MPHnLZaIRlRD2Nq7DFxOcKUdsp2vhCPIlISmCyM7wZfyrPQXYce/bTxV9DPZ+PGHd9IYI/RJe/DcZA7tB576DdvIn2EDSvhkfxQDuiK038KwjbtFFi0+d4cfs2bHXA5m7d5LW2170/O3bnLiEIA==
  template:
    metadata:
      name: minio-secret
      namespace: collector-shop-prod
    type: Opaque
