---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: collector-shop-prod
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBmcifJyws5sxLfd+neS/PvKE/yaKoBRjS3IxHCR/K5ID0QBGm/LETcFvRWmW6ri6Gqp0am6TtTeYhJ7+qbJ9bKaKqAB//5y+8PKRBIGayZS2WoR2OQUhM6WwnbdfLD0qa2KxikWstg3EIfT2NYD8Cy9SjjmGbQzpjlmdCZWUUBdeDrh1fkC5E9WxrBFFYswQ1l5RYetGtTcrxlwkbdoJ4MitsjPMFVEXm6SXgk7lAg4sAZorwWvoMwdUGndsI6NTdmp3YlQgHe5ObUOL6/96yyEQfzxVbgANYeK20ffDLB/cbqeRRK0hzgBDF134ADp90TgWieVIT4zyWDAHNlldNzDQNqHzcKp8Vfa/TAOPr3eiqDjDN1B7ihzDjqh0+gTgnj6Rj2IaotIb6SWFltPR5hXzFZpzZoda83swK6gHJACrDlVlTWu18z85J1ySVvEkJb8DBT32dVCOfsRckqV+fcAWRA2rWH/F1DFqisyVuxm98/qhL4wSFGGz6u4tIuuVcbDJTZupfy5N+JlQq7GWsnXjmCVjtT+etyKr8IGl8Xe50E9HtGQy4vpBO1CkGtQ5lwMN2i27vHIOgwOwM/kA3jvt3Qxw2+MVPG1BlFpWZcferuDzTHRZsc3jueeWpPQ7GzhNHcb9CTR3xryqduDzDGUA50M78joJ6BCh5SR+h6HqklGHCKirOcvsVK+/kkLEdnhKCre5FrXTuw
    MINIO_ROOT_USER: AgByC6E7WklJXBnWbax7piKBbUvD6lPY/RbPt7PosFbL3NcJq/MvMfc0ltDXuHC0OLCAY8PcejwC5jMBTeuQqJsmvg6W1+GA43yYQcD7+6ZRcb1KT3ZlobI5xrVQkFmnD9os/0aQy5YurAd5VlUGI/9/ksi/TaKcPrDO9BcbcGddl7T0CdHZqwYCGNx/3YIzZ8hZek0oo91zcVPs4wUyzqVreIC/MUm/rUqALxhSN762tjTAODwBBc0QRtUVicbNbCT/lXfr2U+z3NO5BnnQCvLrbPlEjvfmBWa4SZtYOQrPoSKiyAQrmwXEuVNgrS3VTr2J5aaOqJiz99z99Kpg4dtIen/SWuv7sAzq97xzyoxxgRwXsmU3EaBho4T090UC4xUG9lPVAio0UmW/R4Cdufjy2HNSHmxITcy15th5D8g7HjmHu2sdzVgZsD8ieoJd+eSKWQ7haGyLp+2xeXgy/OGRJ94OrSqNeIV8FsYWHLhychspsArhP419zi+pJWdFoWgsAF/8lCc0NvwnyCISS9Udm4cYNx9ZID18Uqz9x6bqEtWY+WaBwfp3A580uwlF/tbDvgACZcz5zM0A7jNrCL/VpWTCPk/A+eqVVinzVNHXzI3n2LT/oRBu01/j6MHd1Os/F0lL0hbIZps9IkU+8IlCNNN1ETdUQ3eqeDA/tIyXGXMUzEZs3GhPiBmMa2uuKvjhVX3WBXqnoYwn
  template:
    metadata:
      name: minio-secret
      namespace: collector-shop-prod
    type: Opaque
