apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  namespace: collector-shop-prod
spec:
  template:
    spec:
      containers:
      - name: minio-setup
        image: minio/mc
        envFrom:
          - secretRef:
              name: minio-secret
        command:
        - /bin/sh
        - -c
        - |
          sleep 10;
          mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
          mc mb myminio/collector-shop || true;
          mc anonymous set public myminio/collector-shop;
      restartPolicy: OnFailure
