# SonarCloud Configuration
sonar.host.url=https://sonarcloud.io
sonar.organization=alan-crts
sonar.projectKey=alan-crts_collector-shop
sonar.projectName=Collector Shop Backend
sonar.projectVersion=1.0

# Path to source files
sonar.sources=src
# Path to test files
sonar.tests=src/__tests__
# Pattern to identify test files
sonar.test.inclusions=src/__tests__/**/*.ts

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Exclude node_modules and built files
sonar.exclusions=node_modules/**, dist/**, coverage/**

# JavaScript/TypeScript Specific
sonar.javascript.lcov.reportPaths=coverage/lcov.info
