apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: collector-shop-prod
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: collector_shop
